server:
  port: 9095

  zipkin:
    enabled: true
    baseUrl: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/"
    sleuth:
      sampler:
        percentage: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  enabled: true
  client:
    config:
      workspaces-api:
        connectTimeout: 2000
        readTimeout: 2000
        loggerLevel: full
  hystrix:
    enabled: true



hystrix:
  command:
    default:
      execution.timeout.enabled: true
      execution.isolation.thread.timeoutInMilliseconds: 100
      circuitBreaker:
        enabled: true
        sleepWindowInMilliseconds: 10000
      fallback:
        enabled: false

spring:
  kafka:
    get-topic: get_employee
    put-topic: put_employee
    consumer:
      group-id: employee-spring-integration
      auto-offset-reset: earliest
      enable-auto-commit: false
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      batch-size: 16384
      buffer-memory: 33554432
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer



