spring:
  application:
    name: workspaces-api # ==> This is Service-Id

---
# Items that apply to ALL profiles:
eureka:
  instance:
    appname: workspaces-api  # ==> This is a instance of workspaces-api
#  client:
#    fetchRegistry: true
server:
  port: 9090

---
spring:
  profiles: workspaces-api-01
eureka:
  instance:
    appname: workspaces-api  # ==> This is a instance of workspaces-api
server:
  port: 9091


